language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .

script:
  - python test/test.py
  - python test/test2.py
  - python test/test3.py $user
  - pip install requests-cache
  - python test/test2.py
